### ISSUE TITLE
Documentation: update references to external blogs on Hamilton

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#1046]
**Is your feature request related to a problem? Please describe.**
We need to update https://hamilton.dagworks.io/en/latest/get-started/learning-resources/#external-blogs.

**Describe the solution you'd like**
We need to provide updates for blogs on Hamilton.

Some that come to mind:

* https://blog.dagworks.io/ <-- there a bunch here
* https://pyright.blogspot.com/2024/07/dag-hamilton-workflow-for-toy-text.html
* https://vyom-modi.medium.com/building-a-high-performance-rag-based-ai-with-qdrant-groq-langchain-and-dagworks-hamilton-fb1baa7415bc
* https://blog.getwren.ai/how-do-we-rewrite-wren-ai-llm-service-to-support-1500-concurrent-users-online-9ba5c121afc3

**Describe alternatives you've considered**
N/A

**Additional context**
It would be great to semi-automate this. E.g. make updating this simpler to do, by running a command for example.

**Comment by sikehish** [comment]
I'd like to take this up!

**Comment by skrawcz** [comment]
> I'd like to take this up!

Great thank you. Assigned. Do you have an understanding of where and what to change?

**Comment by sikehish** [comment]
If I've understood the issue correctly, we want to have the latest blogs in the external blogs section. Is that correct? If that's the case, then I was thinking if I could make use of a substack API(if it exists)/scrape https://substack.com/@dagworks/posts for the posts and then update the posts in external blog sections in the markdown file.

**Comment by skrawcz** [comment]
> If I've understood the issue correctly, we want to have the latest blogs in the external blogs section. Is that correct? If that's the case, then I was thinking if I could make use of a substack API(if it exists)/scrape https://substack.com/@dagworks/posts for the posts and then update the posts in external blog sections in the markdown file.

yep pretty much. You'd need to filter to posts that are about hamilton. Otherwise there's a few other posts that are linked in the issue that should also be added.

**Comment by skrawcz** [comment]
@sikehish yes that's fine.

I think using a date cut off is fine. Since that's how we'd update/run it. Pull posts older than X and add to the docs please :)

**Comment by sikehish** [comment]
Hi @skrawcz . I was able to fetch the relevant data fro blog.substack.io using headless web scraping. I'll start making the commits after the other PR #1194 gets through, to ensure that the commit history remains true to what the PR is.

**Comment by sikehish** [comment]
HI @skrawcz . I've raised a PR #1208. Let me know if any changes need to be made.
