### ISSUE TITLE
Can you update the the Slack link?

### ISSUE THREAD

**Issue by ytang137** [DAGWorks-Inc/hamilton#1055]
Hi, could you update the Slack link? I'd love to join the community, but the links in various places all lead to `This link is no longer active`. Thank you!

# Current behavior

## Stack Traces
(If applicable)

## Screenshots

<img width="632" alt="Screen Shot 2024-07-22 at 9 14 34 PM" src="https://github.com/user-attachments/assets/5cf65d01-f532-4723-85c3-9cdb0f5d7549">

## Steps to replicate behavior
1.

## Library & System Information
E.g. python version, hamilton library version, linux, etc.

# Expected behavior

# Additional context

**Comment by skrawcz** [comment]
Thanks for flagging - https://join.slack.com/t/hamilton-opensource/shared_invite/zt-2niepkra8-DGKGf_tTYhXuJWBTXtIs4g this should work. I'll go update.
