### ISSUE TITLE
Slow import of hamilton's Builder

### ISSUE THREAD

**Issue by giladrubin1** [DAGWorks-Inc/hamilton#1059]
## Current behavior
Importing the `Builder` from `hamilton.driver` takes approximately 4-5 seconds, while the rest of the package imports are instant.

### Steps to replicate behavior
1. Open a VSCode notebook
2. Run the following import:
   ```python
   from hamilton.driver import Builder
   ```
3. Observe that the import takes 4-5 seconds to complete

## Library & System Information
- Hamilton library version: 1.72.1
- Environment: VSCode notebooks

## Expected behavior
The import of `Builder` from `hamilton.driver` should be as fast as other package imports.

## Additional context
This slow import is specifically noticed when using VSCode notebooks. It would be helpful to know if this behavior is reproducible in other environments or if it's specific to VSCode notebooks.

**Comment by skrawcz** [comment]
Thanks @giladrubin1 .

This is likely the plugins being loaded (my hypothesis). If you have a lot of libraries in your environment this can happen - I assume you have a lot in your python environment? 

Otherwise the plugin loading could be optimized for sure.

**Comment by giladrubin1** [comment]
I do have several libraries in my environment... I did some basic testing with import-waterfall and if I read the graph right - it does show that the import is affected by other libraries. 

However, I would expect Hamilton's builder to not be affected by other libraries in this way. Especially since most of them are not used in the context of that driver.

**Comment by skrawcz** [comment]
Yes, agreed. If you haven't imported them beforehand, Hamilton shouldn't
either -- that's at least my view.

**Comment by Dev-iL** [comment]
@giladrubin1 which python version are you on? If >=3.12, could you please see if [enabling lazy imports](https://peps.python.org/pep-0690/#specification) helps?

```python
importlib.set_lazy_imports()
```

**Comment by giladrubin1** [comment]
I'm using python 3.10

**Comment by Dev-iL** [comment]
That's fine - disregard that suggestion - looks like that PEP was rejected anyway. Maybe something like [this](https://stackoverflow.com/a/54616590/3372061) could work:

```python
def __getattr__(name):
    if name == "module_xyz_it_takes_long_to_load":
        return _lazy_init_function_for_xyz()

    # Implicit else
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
```
 I'll give that approach a try in one of my personal projects and see if it's worth considering.

**Comment by giladrubin1** [comment]
I want to emphasize that I'm not looking for a workaround.
I think this needs to be solved on the package level to avoid these eager imports.

**Comment by Dev-iL** [comment]
If you're referring to my replies, I did not suggest workarounds, but ways to modify the imports of hamilton itself to be lazy. I suggested one of us tries it was to enaure this is indeed a viable approach to introduce into hamilton.

**Comment by giladrubin1** [comment]
Ah, I see. Yes, I did not understand that from your previous comments. Thank you for that.
I'm currently not intending to work on this fix, so perhaps the Hamilton team will use your suggestion :)

**Comment by zilto** [comment]
PR was merge in hope to fix this issue. [Read the docs for more info!](https://hamilton.dagworks.io/en/latest/how-tos/extensions-autoloading/)
