### ISSUE TITLE
Provide dockerx setup for docker builds

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#1064]
**Is your feature request related to a problem? Please describe.**
We need to create multi platform docker builds.

Right now the process is manual. We'd like to have dockerx do it.

This is a good issue if you know docker.

**Describe the solution you'd like**
1. Have instructions for building the Hamilton UI with dockerx.
2. nice to have: github action setup to build docker.

**Comment by sikehish** [comment]
I'd like to take this up. I'm quite familiar with docker.
I'd create a script(probably a shell script), where in I'd have docker buildx related commands(and for the desired target arch). Github action workflow could also be written to automate builds with dockerx.
Let me know if you'd want me to take a different approach.

**Comment by skrawcz** [comment]
> I'd like to take this up. I'm quite familiar with docker. I'd create a script(probably a shell script), where in I'd have docker buildx related commands(and for the desired target arch). Github action workflow could also be written to automate builds with dockerx. Let me know if you'd want me to take a different approach.

Thanks! Sounds good. Current instructions are here - https://github.com/DAGWorks-Inc/hamilton/tree/main/ui. Please let me know if you have questions!

**Comment by sikehish** [comment]
> > I'd like to take this up. I'm quite familiar with docker. I'd create a script(probably a shell script), where in I'd have docker buildx related commands(and for the desired target arch). Github action workflow could also be written to automate builds with dockerx. Let me know if you'd want me to take a different approach.
> 
> Thanks! Sounds good. Current instructions to build an image are here - https://github.com/DAGWorks-Inc/hamilton/tree/main/ui. Please let me know if you have questions!

Hi,
I've created a shell script for building(using buildx) and pushing images: https://github.com/sikehish/hamilton/blob/main/ui/buildx_and_push.sh . Is that you were looking for? Do you want me to make the exisiting docker compose files (in ui) to make use of multi platform builds?

**Comment by skrawcz** [comment]
@sikehish yes and:

1. please extend to build over some common platform types
2. version should match the latest sf-hamilton-ui library version; we'll also want to update the "latest" tag to point to it.

Feel free to open up a PR and we can chat on it there.

**Comment by sikehish** [comment]
Hi @skrawcz.
I've created a new PR #1194. I'll be adding other common platform types soon. Let me know if anything else needs to be implemented/changed.

**Comment by skrawcz** [comment]
> Hi @skrawcz. I've created a new PR #1194. I'll be adding other common platform types soon. Let me know if anything else needs to be implemented/changed.

Looks good - left one comment. I'll get someone from the team to try it Monday.

**Comment by skrawcz** [comment]
Thanks @sikehish ! Merged.
