### ISSUE TITLE
TypeError: dataloader() takes no arguments

### ISSUE THREAD

**Issue by Dev-iL** [DAGWorks-Inc/hamilton#1084]
The example code for `function_modifiers.dataloader` (and `datasaver`) doesn't run correctly.

# Current behavior

Running the code in the dataloader/datasaver doctstring results in a `TypeError`.

## Steps to replicate behavior
Run the code in the [dataloader](https://hamilton.dagworks.io/en/latest/reference/decorators/dataloader/#example-usage) or [datasaver](https://hamilton.dagworks.io/en/latest/reference/decorators/datasaver/#example-usage) examples.

## Library & System Information
Windows 10, Python 3.12, sf-hamilton 1.73.0

# Expected behavior
The example code should not throw an error.

**Comment by Dev-iL** [comment]
I should mention that adding `()` at the end of the decorator makes this work.

**Comment by skrawcz** [comment]
@Dev-iL do you mean

```python
@datasaver
def my_function(...)-> ...
```

Yes the above does not work. In the examples you'll notice they do:

```python
@datasaver()
def my_function(...)-> ...
```

This is because the decorator is an object that needs to be instantiated. We get away with it in the other decorators because you need to pass in an argument. But for this one, we don't at the moment.

**Comment by skrawcz** [comment]
🤦  d'oh thanks I missed that. I was thinking about https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/materialization/datasaver_dataloader_example. I'll fix. Thanks

**Comment by skrawcz** [comment]
Fixed with #494 . Thanks @Dev-iL !

**Comment by Dev-iL** [comment]
Np. Surely you meant #1085 ;)

**Comment by skrawcz** [comment]
> Np. Surely you meant #1085 ;)

Yes -- heh moving too quickly this morning ! thanks 😅 .
