### ISSUE TITLE
data_loaders

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#1122]
# Is your feature request related to a problem? Please describe.
A lot of DS want a notebook to get started with, not a python script -- these can be too intimidating.

# Describe the solution you'd like
We should make sure our examples all have a jupyter notebook to mirror the "run.py" file. That way people can see how things are exercised and then they can use a notebook to try things out.

E.g. we want each example to have a notebook kind of like the [hello world example](https://github.com/DAGWorks-Inc/hamilton/blob/main/examples/hello_world/my_notebook.ipynb).

This issue is for the `data_loaders` example.

**Comment by eoagyen** [comment]
@skrawcz Thanks for the confirmation! I'm happy to take on the `data_loaders` task. Please go ahead and assign it to me.
