### ISSUE TITLE
Developer_setup.md on package Installation.

### ISSUE THREAD

**Issue by seyawudba** [DAGWorks-Inc/hamilton#1139]
**Is your feature request related to a problem? Please describe.**
When installating the packages using z shell, one is likely to encounter a problem as the brackets treated as pattern matching symbols. 

**Describe the solution you'd like**
To avoid use escape characters before the brackets.

**Describe alternatives you've considered**
Wrapping the argument in quotes will also prevent the argument from being treated as pattern matching symbols in zsh.

**Additional context**
![WhatsApp Image 2024-09-13 at 16 24 49](https://github.com/user-attachments/assets/6250089c-d29e-4b64-951b-1facc5e6bb45)

**Comment by elijahbenizzy** [comment]
Yes, agreed that we should have quotes on everything. If you don't mind, a PR that adds quotes to the bracketed install commands would be quite welcome!

**Comment by seyawudba** [comment]
Alright please, I have worked on that and will raise a PR asap.

**Comment by zilto** [comment]
Merged in #1141
