### ISSUE TITLE
reusing_functions

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#1179]
# Is your feature request related to a problem? Please describe.
A lot of DS want a notebook to get started with, not a python script -- these can be too intimidating.

# Describe the solution you'd like
We should make sure our examples all have a jupyter notebook to mirror the "run.py" file. That way people can see how things are exercised and then they can use a notebook to try things out. Note: we should use the `jupyter_magic` where appropriate in the notebook.

E.g. we want each example to have a notebook kind of like the [hello world example](https://github.com/DAGWorks-Inc/hamilton/blob/main/examples/hello_world/my_notebook.ipynb).

This issue is for the reusing_functions example.

**Comment by eoagyen** [comment]
@skrawcz I will work on this issue. Thanks
