### ISSUE TITLE
Tag generated/literal nodes

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#122]
**Is your feature request related to a problem? Please describe.**
Some nodes are going to be generated by DAG operations/decorators. E.G. `value` will almost always generate a node. We should know what these are to make it clear to the user.

**Describe the solution you'd like**
Tags that indicate that this is a literal. Then the nodes callable is `() -> value` we could reference that/expose it in the variable.

**Describe alternatives you've considered**
We might also want to track lineage for these, given that in `@resolve` they come from a config element. This is tricky in the case that we have a list of items.

**Comment by skrawcz** [comment]
need more context here. closing for now.
