### ISSUE TITLE
Allow `save_to` to function with `extract_fields` or `@parameterize`

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#153]
**Is your feature request related to a problem? Please describe.**
Currently you can't save multiple from the same function. Would be nice. We can probably use the `target_` to specify which one gets saved. 
```python
@save_to.parquet(
    path=source('save_to_value_1'), 
    target_='value_1', 
    output_name_='value_1_saved')
@save_to.csv(
    path=source('save_to_value_2'), 
    target_='value_2', 
    output_name_='value_2_saved')
@parameterize(
     value_1={'foo' : value(...)},
     value_2={'foo' : value(...)},   
)
def value_n(foo: ...) -> pd.DataFrame:
    return ...
````
**Describe the solution you'd like**
Change `save_to` from a `SingleNodeNodeTransformer` to the standard one, with an error when there are multiple nodes outputted and there's ambiguity.

**Describe alternatives you've considered**
Not doing this. Problem is an API could get verbose. 

**Additional context**

**Comment by zilto** [comment]
We suggest using the [materializer API](https://hamilton.dagworks.io/en/latest/concepts/materialization/) if you can't directly decorate a Python function
