### ISSUE TITLE
Merging of dags

### ISSUE THREAD

**Issue by tim-habitat** [DAGWorks-Inc/hamilton#167]
**Is your feature request related to a problem? Please describe.**
I have several workflows / models that use different `hamilton` dags, they are created independently for cleaner code. However, i would love to be able to merge the 2 (or more) dags and process common features only once. 

**Describe the solution you'd like**
A method on a dag that allows for something like:
```python
all_features_dag = dag1.merge(dag2)
```

**Describe alternatives you've considered**
I considered tagging some features (dag's node) with `common` or something similar, processing those only once and then processing the other ones in parallel. Though this requires coordination between task and is a bit of a pain point. 
Haven't implemented this yet.

**Additional context**
Here is a not too great drawing of what i am thinking - in this case feature 2 and 5 are redundantly computed if the dags are run independently, but we could join them and thus save compute on those!

<img width="1301" alt="Screenshot 2023-05-17 at 10 02 31" src="https://github.com/DAGWorks-Inc/hamilton/assets/86600518/9b6db9d2-9976-4e6c-b743-2cb5cf72a50e">
Let me know if i should clarify some points, or help in any ways!

Thank you for a great library! 🤙

**Comment by tim-habitat** [comment]
thanks for the prompt reply!!

I used [excalidraw](https://excalidraw.com/) for the drawing.

Yeah I agree they might be different - and tbh i haven't completely thought this through but there might be some unicity needed in the feature names or merging those nodes as considering them as the same ?

1. Oh that's nice, i didn't think of this but this might scratch the itch for now. 

3. I think indeed the comment gets at what i'm trying to go at - but in some sense still requires a sense of hierarchy between the "main" dag and sub-dags. 
I was thinking more of parallel dags that once getting merge kind of handle that on its own. Perhaps this gets to the same thing but i would just be nice not to have to figure out which features should be in the main / subdags.

I guess the only difference from the approach i'd like and those you suggested is that "i'm lazy" and would like to just define a bunch of module that may have redundant features and merge that and build a dag that satisfies each of the requirement in an optimal way.

**Comment by skrawcz** [comment]
> Yeah I agree they might be different - and tbh i haven't completely thought this through but there might be some unicity needed in the feature names or merging those nodes as considering them as the same ?
> ...
> I guess the only difference from the approach i'd like and those you suggested is that "i'm lazy" and would like to just define a bunch of module that may have redundant features and merge that and build a dag that satisfies each of the requirement in an optimal way.

@tim-habitat I think I understand. One of the design principles of Hamilton is to try to make it easy to determine the code that produced and output. So right now, for example, when you provide overlapping "functions names" Hamilton won't like that (either in the same or multiple modules). Therefore you can use something like [`@config`](https://hamilton.readthedocs.io/en/latest/reference/api-reference/decorators.html#config) and annotate them to know which one should exist when, or swap out the right python modules. This then makes it clear which one is used when.

> Oh that's nice, i didn't think of this but this might scratch the itch for now.

Great let us know how you get on! Otherwise I think your merge idea is interesting, but curious to see whether playing with `@config` and your python module structure gets you there instead.

**Comment by skrawcz** [comment]
@tim-habitat seeing that habitat.energy is in the UK - just wanted to mention a [meet-up](https://www.meetup.com/agile-data-london/events/293589063/) that could be of interest to you.

**Comment by tim-habitat** [comment]
> when you provide overlapping "functions names" Hamilton won't like that (either in the same or multiple modules)

Yeah true, so i think it is fair to assume that if a function has the same name it is the same function and the dag can merge on that. or would there be cases where we wouldn't want to do that ?

>Great let us know how you get on! 

Yeah i'll keep you posted on how we do this! 

> just wanted to mention a [meet-up](https://www.meetup.com/agile-data-london/events/293589063/) that could be of interest to you.

Oh nice thanks for sharing, yeah i'm in london - i'll definitely try to be there! :)

**Comment by skrawcz** [comment]
> Yeah true, so i think it is fair to assume that if a function has the same name it is the same function and the dag can merge on that. or would there be cases where we wouldn't want to do that ?

It depends if they have the same dependencies or not -- which version do you pick? If they're 1-1 then yeah shouldn't be an issue, but if not -- what should a user do? :)

**Comment by tim-habitat** [comment]
I agree it could be tricky, but i think there are opinionated ways to do it. 
In my mind right now what would make the most sense is a first pass / checks that verifies that each common node has the same "parents", if not, `raise`. Of course with a clear error message that explain this.
This would preserve the unicity of function name to node and dependency lineage i think.

Also, for reference `networkx` compose all [method](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.operators.all.compose_all.html#networkx.algorithms.operators.all.compose_all) could be a good way to present the api.

**Comment by skrawcz** [comment]
Please reopen if new thoughts / needs have arized. We are thinking about driver chaining, but right now no impetus to implement it yet.
