### ISSUE TITLE
Versioning of features / nodes

### ISSUE THREAD

**Issue by tim-habitat** [DAGWorks-Inc/hamilton#175]
**Is your feature request related to a problem? Please describe.**
I'd love to know what version a feature was created with. I could just use a git commit hash, but it may be that between 2 commits, the code though which the feature flows hasn't changed so the version should be the same. 
This would be ideal in situation where we would need to pre-process a large amount of feature to be used later, than some process could just check whether the features were created with the same "version". If not, recompute only those ones.

**Describe the solution you'd like**
Each features / last node of a graph has a version attached to it. The version depends on the code within the function used to create the feature but also of all the parents. 
I feel in some ways i'd like the solution to be clear / easy. Like a hash of the code of the node.

i feel it might be tricky to think about for nodes that interact with `io` but perhaps that should be dealt by the user. 

**Describe alternatives you've considered**
I considered using git commit hash, but features code changes much less frequently than the overall repo. I considered implement something hacky myself but haven't got to it.

**Additional context**
![Screenshot 2023-05-23 at 15 03 52](https://github.com/DAGWorks-Inc/hamilton/assets/86600518/d73f649e-5aec-4f8e-8c2c-9ae1e3e6091b)

**Comment by skrawcz** [comment]
@tim-habitat thanks for the idea! @elijahbenizzy and I have talked about this, as this is very close in functionality to "caching"/"check pointing". Would love to chat more about your use case. Would you be up for a call? Feel free to [jump into slack](https://join.slack.com/t/hamilton-opensource/shared_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg) and we can schedule a time there.

**Comment by zilto** [comment]
some features are now available under the `h_diskcache` plugin and the `hamilton` CLI. Continuing discussion in #728
