### ISSUE TITLE
Allow multiple use of load_from 

### ISSUE THREAD

**Issue by wentao-lu** [DAGWorks-Inc/hamilton#219]
**Is your feature request related to a problem? Please describe.**
It's pretty common for a downstream node to have multiple upstream nodes. Often times we found that it would be helpful if we can load from multiple upstreams instead of only one.

Currently this usage is not supported.

```
@load_from.json("A")
@load_from.json("B")
def function(A, B):
```

**Describe the solution you'd like**
I don't have any preference on one or the other, as long as multiple upstream nodes can be injected from load_from.

**Describe alternatives you've considered**
Keep the current limitation but expand the function to allow multiple injects. 
```
@load_from.json(
  injects=dict(
    A=xxx,
    B=xxx,
  )
)
```

**Additional context**

```
.venv/lib/python3.9/site-packages/hamilton/function_modifiers/base.py:113: in __call__
    raise ValueError(
E   ValueError: Got multiple decorators for decorator @<class 'hamilton.function_modifiers.adapters.LoadFromDecorator'>. Only one allowed.
```

**Comment by elijahbenizzy** [comment]
So yeah, this is an inherent limitation of how we implement it, as a [NodeCreator](https://github.com/DAGWorks-Inc/hamilton/blob/e1fabdeff0813645cfc9ed8bcaabfddf9941843e/hamilton/function_modifiers/base.py#L186). A NodeCreator takes a function and turns it into a node. 

I think the best way to do this would be to implement this as a [SubdagModifier](https://github.com/DAGWorks-Inc/hamilton/blob/e1fabdeff0813645cfc9ed8bcaabfddf9941843e/hamilton/function_modifiers/base.py#L217). This takes a subdag (an already generated set of nodes), and modifies it in some way.

The way to do this with a `SubdagModifier` would be pretty straightforward:
1. Find the inject parameter
    - if the subdag has only one input (dependency of a source node), then its that input
    - if the subdag has multiple inputs, we need to rely on the `inject_` parameter
2. Add a "filter" node that just returns the data source, this will have the same name as the inject parameter
3. Add those both to the subdag, along with the original node 

Note that it won't have the same exact structure, so we need to examine whether we have it locked in the contract (there's now an extra node). The other way to do this is to combine (2) and (3) by modifying the source node to do the filtering.

**Comment by skrawcz** [comment]
@wentao-lu mind trying out #221 to verify that it works for you?

e.g. `pip install git+ssh://git@github.com/dagworks-inc/hamilton.git@multiple-load-from` and try your code.

**Comment by elijahbenizzy** [comment]
This is complete!
