### ISSUE TITLE
Pandas Series output objects name

### ISSUE THREAD

**Issue by zilto** [DAGWorks-Inc/hamilton#224]
**Is your feature request related to a problem? Please describe.**
When a function node receives a pandas Series as input and outputs a new pandas Series derived from it, the Series keeps the name of the input object.

For example:
```
timestamp = pd.Series(name="event_timestamp", dtype=datetime64[ns])

def driver_id() -> pd.Series:
  return pd.Series(name="driver_id", dtype=int)

def day_of_week(timestamp: pd.Series) -> pd.Series:
  return timestamp.dt.day_of_week
  
def count_per_day_of_week(driver_id: pd.Series, day_of_week: pd.Series) -> pd.Series:
  df = pd.concat([driver_id, day_of_week], axis=1)
  return df.groupby(["driver_id", "day_of_week"]).count().reset_index(drop=True)
```
Here, the code will fail because the `groupby` won't recognize the name `day_of_week`. The name associated with `day_of_week` remains `timestamp`, i.e., the name associated with the input of the function `day_of_week()`.

**Describe the solution you'd like**
The above example is fixed by wrapping the result of `day_of_week` like this:

```
def day_of_week(timestamp: pd.Series) -> pd.Series:
  return pd.Series(timestamp.dt.day_of_week, name="day_of_week")
```

It would be great if this could be handled automatically, or at least catch this type of error to provide a relevant message.

**Comment by skrawcz** [comment]
Yeah my worry with enforcing naming is that we mutate things.

Instead I think the check that the name matches the function name isn't a bad one. Otherwise the clearer thing to do is what you describe I think -- rather than get the framework to enforce it.

**Comment by zilto** [comment]
Agreed that having the pandas default is better than enforcing another arbitrary default. Thinking about it, it is the kind of check that should be part of a unit test and not necessarily data validation because it is a property of the code logic that should be invariant to data. 

Closing the issue!
