### ISSUE TITLE
First class pyspark support

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#248]
**Is your feature request related to a problem? Please describe.**
Pyspark dataframes might require too many joins at the end -- we've seen this happen. This adds a nice, clean support for this.

**Describe the solution you'd like**
Concept of `mapgroup` to group UDFs. Allows you to switch between:
1. Python primitives UDFs
2. Pandas UDFs
3. Functions of pyspark dataframes

Basically this is a special subdag that applies a series of map transformations in order. Here is an example:

```python
import pyspark.sql as ps
from hamilton.htypes import column as _


# implemented using pandas series
def d(a: _[pd.Series, int], b: _[pd.Series, float]) -> _[pd.Series, float]:
	"""Pyspark UDF with pandas series"""
	...

def e(c: _[pd.Series, int]) -> _[pd.Series, int]:
	"""Pyspark UDF with pandas series"""
	...

# implemented using pyspark transforms, TBD on exactly what this would look like

def d(df: ps.DataFrame) -> ps.DataFrame:
	return d.withColumn(...)

def e(df: ps.DataFrame) -> ps.DataFrame:
	return df.withColumn(...)

# Implemented using primitives, less efficient

def d(a: int, b: float) -> float:
	"""Pyspark UDF with python primitives"""
	...

def e(c: int) -> int:
	"""Pyspark UDF with python primitives"""



def df() -> ps.DataFrame:
	return _load_my_data() # columns a,b,c,f

@h_spark.mapgroup(
	d,e,
	select=['d', 'e', 'f'],
)
def df_processed(df: ps.DataFrame) -> ps.DataFrame:
	"""This does the following:
	1. Applies d,e udfs in a linear order to the same dataframe
	2. Selects `d`, `e`, `f` from the result
	3. returns the final dataframe, passing it to the user
	"""
	return df # or do something with it...
```

see illustration for explanation: 
![Pyspark Hamilton](https://github.com/DAGWorks-Inc/hamilton/assets/3886307/b74f2813-ac70-447c-95df-32063744a10a)

Note this is actually isomorphic to the dataframe UDF adapter. As subdag is to the standard driver, this is to the UDF adapter.
**Describe alternatives you've considered**

We already have a pyspark UDF adapter.

**Comment by skrawcz** [comment]
I believe a version of this was completed.
