### ISSUE TITLE
pandas pickle

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#292]
Implement https://pandas.pydata.org/docs/reference/io.html#pickling as a data saver/loader.

It should go into `pandas_extensions.py`, one class for the writer, on class for the reader, e.g. much like how this [polars CSV reader and writer](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L42-L213) are structured.

**Comment by benhhack** [comment]
Keen to take this on.
