### ISSUE TITLE
ImportError for polars <0.18

### ISSUE THREAD

**Issue by janhurst** [DAGWorks-Inc/hamilton#295]
Importing the driver module via `from hamilton import driver`, I'm getting an `ImportError` on 'CsvQuoteStyle` from `polars.type_aliases`

# Current behavior
Import Error

## Screenshots
![image](https://github.com/DAGWorks-Inc/hamilton/assets/16224889/50de2452-57ba-4da2-b987-237c36919f48)

## Steps to replicate behavior
1.

## Library & System Information
Linux (ubuntu) devcontainer
Python 3.10
sf-hamilton 1.27.0
polars 0.17.15

# Expected behavior
driver imported and no ImportError

# Additional context
Looks like this is in polars >0.18?
https://github.com/pola-rs/polars/blob/abab4970d8e4895309f3f66ccf4c1d8e84cbfdfd/py-polars/polars/type_aliases.py#L81
and the import here:
https://github.com/DAGWorks-Inc/hamilton/blob/319e029bbb5c0249ab39ecae8a419324ea59f145/hamilton/plugins/polars_extensions.py#L12C24-L12C24

maybe needs some sort of guard on polars version, I couldn't quite see how thats setup from hamilton's side?

**Comment by skrawcz** [comment]
@janhurst I'm pretty confident this will fix it -- https://github.com/DAGWorks-Inc/hamilton/pull/296 mind validating?
