### ISSUE TITLE
Make resolve's when default to ResolveAt.CONFIG_AVAILABLE

### ISSUE THREAD

**Issue by janhurst** [DAGWorks-Inc/hamilton#304]
**Is your feature request related to a problem? Please describe.**
Presently the `@resolve` decorator needs a `when` argument to be passed. The only supported argument is `ResolveAt.CONFIG_AVAILABLE`.

**Describe the solution you'd like**
Make the `when` argument a keyword argument with a default of `ResolveAt.CONFIG_AVAILABLE`

**Describe alternatives you've considered**
Making a custom decorator `@resolve_at_config_available` that wraps this and defaults

**Additional context**
I find I am scattering `when=ResolveAt.CONFIG_AVAILABLE` around plus it's import which feels a bit boilerplatey... sry I'm being lazy here rather than submitting a PR :(

I've also not really looked to see if theres any guidance around where the `when` functionality might be expanded, but regardless it does feel a bit like a default would still be reasonable?

**Comment by elijahbenizzy** [comment]
OK, so I think that the immediate solution for you is a custom wrapper decorator:

```python
# custom_decorators.py
from hamilton.function_modifiers import resolve as resolve_to_overwrite, ResolveAt

def resolve(decorate_with: Callable[..., NodeTransformLifecycle]):
    return resolve_to_overwrite(when=ResolveAt.CONFIG_AVAILABLE, decorate_with)
```

Then just replace your `resolve` calls with:

```python
from custom_decorators import `resolve`
```

Note if you were feeling fancy you could even monkey-patch hamilton's `resolve` (although no guarentees that would be safe).

TBD whether we want this globally. Currently its the only existing option, but there are a few reasons I'm hesitant to remove it:

1. The idea is to eventually (if we choose this approach) have multiple options, and this becomes a base-layer for the API: `ResolveAt.RUNTIME` should be able to use runtime-specific information for some chaotic DAGs, effectively doing what `Parallelizable` does, but more idiomatically (TBD whether we decide to do that). That said, it could easily be folded into another function: `resolve_from_config`, as you suggested, or `resolve_at_runtime` as I've been mulling over.
2. I think this creates a pretty clear readability improvement -- `resolve` is unclear to someone reading the code, whereas `resolve_from_config` or `ResolveAt.CONFIG_AVAILABLE` both make it very clear where the data is coming from...
3. The final API I don't really want resolve at all -- specifically, I'd like to do something like this:

```python
from hamilton.function_modifiers import from_config

@extract_columns(
    *from_config('columns_to_extract',  list)
)
def dataframe_to_extract() -> pd.DataFrame:
    ...
    
@parameterize(
   **{key: source(value) for key, value in from_config('parameterizations',  dict).items()}
)
def  parameterized_fn(value: ..., ...) -> ...:
    ...
```

The cool thing is that, if you have common config items across the codebase, you could build your own wrappers:

```python
MY_COLUMNS = from_config('columns_to_extract',  list)
@extract_columns(
    *my_columns
)
def first_extract() -> pd.DataFrame:
    ...

@parameterize(
    **{f"{col}_processed": source(col) for col in MY_COLUMNS}
)
def then_process(col: pd.Series) -> pd.DataFrame
    
@inject(
    cols=group(*[f"{col}_processed" for col in MY_COLUMNS])
)
def then_sum(cols: List[pd.Series]) -> pd.Series:
    return sum(cols)
```

Then, if we were feeling totally crazy, we could replace `from_config` with `from_prior_node`, and have some truly dynamic stuff.

Getting ahead of myself and I doubt this is worth it now or soon, but wanted to draw out these ideas before I forget...

**Comment by janhurst** [comment]
>  That said, it could easily be folded into another function: resolve_from_config, as you suggested, or resolve_at_runtime as I've been mulling over.

Got tinkering with this again this morning and I rolled a `@resolve_from_config` which feels much nicer

> but there are a few reasons I'm hesitant to remove it

I wouldn't (wasn't?) advocating to remove... for me it was more about a default that is the only option, and I was more worried that if it was perhaps made a kwarg style default then it might be painful down the track if a new option comes along which is a "better" default and causes some migration pain

... hence I think I'm +1 on getting a `@resolve_from_config` wrapper :)

> The final API I don't really want resolve at all -- specifically, I'd like to do something like this:
>```
>from hamilton.function_modifiers import from_config
>```

This is exactly where I'm headed... I have a thinger' list that I'm providing as config. 99% of the time its just a default coming from another part of code i.e `get_thingers(): list` but I do want to be able to modify that list occasionally. My `decorate_with`'s are just lambdas that are expanding out the `thingers`. I sort of want to do this at runtime but that is being driven more about having to build a large DAG that usually I'm just asking for a small set of outputs from

**Comment by aglove2189** [comment]
@janhurst could you share your `@resolve_from_config` wrapper? This is definitely something I could utilize. Thanks in advance!

**Comment by skrawcz** [comment]
@janhurst maybe even a contribution? ;)

**Comment by janhurst** [comment]
My wrapper looks something like:

```python
def resolve_from_config(decorate_with: Callable[..., NodeTransformLifecycle]):
    """Resolve when config is available."""
    return resolve(when=ResolveAt.CONFIG_AVAILABLE, decorate_with=decorate_with)
```

I've made a PR here https://github.com/DAGWorks-Inc/hamilton/pull/828, apologies I just threw something together. I'm not actively working on the projects that I was using this for at the moment and don't have a good dev environment setup.
