### ISSUE TITLE
driver.visualize_execution should allow overrides

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#308]
**Is your feature request related to a problem? Please describe.**
Pretty essential piece of execution -- this could help debugging

**Describe the solution you'd like**
`dr.visualize_execution` should allow overrides -- this would visualize the upstream nodes from overrides/inputs taht would be executed.

**Comment by maxjacu** [comment]
Another reason: If one can execute dag using overrides, one should be able to visualize that exact dag.

**Comment by elijahbenizzy** [comment]
Implemented! https://github.com/DAGWorks-Inc/hamilton/pull/313
