### ISSUE TITLE
Cleaner Synchronization between materializers + save_to

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#310]
**Is your feature request related to a problem? Please describe.**
There's an isomorphism between the two -- one should be able to specify the name of a `load_to` node in `.materialize` as a materializer.

**Describe the solution you'd like**
```python
# in modules
@save_to(path=value("output.csv"), output_name_="foo_output")
def foo() -> pd.DataFrame:
    ...
```

Then in materializer you'd have:

```python
dr.materialize(['foo_output'])
```
This would be the same as calling it as a variable, excpet syntactically more clean.

**Comment by zilto** [comment]
Things to streamline:

`from_` has kwarg `target`
`to` has kwarg `id`
`@save_to` has kwarg `output_name_`
`@save_to` default name is `"save.NODE_NAME"`

**Comment by skrawcz** [comment]
This seems stale.
