### ISSUE TITLE
Enhanced viz for pyspark

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#316]
**Is your feature request related to a problem? Please describe.**
We have two types of dependencies:
1. Logical (how the DAG was defined)
2. Physical (how it is executed)

Currently we think of these as the same, but the viz is ugly. See @roelbertens comment here: https://github.com/DAGWorks-Inc/hamilton/pull/309#issuecomment-1701614097. 

**Describe the solution you'd like**
- The logical dependencies should shape the DAG.
- The physical ones should be marked differently. 
- Perhaps this should be adjustable
 
**Describe alternatives you've considered**
Moving it to visualization within h_spark so we don't have to generalize

**Additional context**

See line from `darkshore_likelihood` to `durotar_likelyhood` here: 
![image](https://github.com/DAGWorks-Inc/hamilton/assets/3886307/11a4502c-06d5-411c-bf71-b24570c9440e)

**Comment by skrawcz** [comment]
we added this with custom styling and "@schema" decorator.
