### ISSUE TITLE
pandas excel

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#342]
1. Implement https://pandas.pydata.org/docs/reference/io.html#excel as a data saver/loader.
It should go into pandas_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [pandas pickle reader and writer](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) are structured.
2. There should be requisite tests to exercise the functionality.
3. Then an example should be added to the [example/pandas/materialization example](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/pandas/materialization). It should just add to the existing materializers; yes this only exercises the writer.

**Comment by benhhack** [comment]
@skrawcz I'll take this one

**Comment by benhhack** [comment]
Hey @skrawcz , still haven't got my Python working this side so probably best to take me off this issue.

**Comment by skrawcz** [comment]
@tyapochkin implemented this, so it's closed.
