### ISSUE TITLE
pandas xml

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#352]
Implement https://pandas.pydata.org/docs/reference/io.html#xml as a data saver/loader.
1. It should go into pandas_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [pandas pickle reader and writer](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) are structured.
2. There should be requisite tests to exercise the functionality.
3. Then an example should be added to the [example/pandas/materialization example](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/pandas/materialization). It should just add to the existing materializers; yes this only exercises the writer.
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by JoJo10Smith** [comment]
I will be working on this ticket.

**Comment by JoJo10Smith** [comment]
I had trouble merging the suggestions in my previous commit that I lost access to it. I am still new to GIt so it was just easier for me to close that and make another PR (#356)

**Comment by skrawcz** [comment]
implemented!
