### ISSUE TITLE
pandas html

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#369]
Implement https://pandas.pydata.org/docs/reference/io.html#html as a data saver/loader.

1. It should go into pandas_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [pandas pickle reader and writer](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) are structured.
2. There should be requisite tests to exercise the functionality. Note: new style. We want a single test that exercises the save and then load functionality, using what was just saved.
3. Then an example should be added to the [example/pandas/materialization example](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/pandas/materialization). It should just add to the existing materializers; yes this only exercises the writer (i.e. saver).
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by JoJo10Smith** [comment]
I'll be working on this ticket.

**Comment by skrawcz** [comment]
Implemented!
