### ISSUE TITLE
Garbage Collection for Parallelism

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#373]
**Is your feature request related to a problem? Please describe.**
Parallelism/task-based dynamic execution appears to hold onto all of the intermediate information. This is suboptimal for i/o driven workflows that handle large data but only return small pieces.

**Describe the solution you'd like**
Garbage collect all intermediate data. Should be as simple as pruning this to just the results we need? https://github.com/DAGWorks-Inc/hamilton/blob/5ab636068c89e759acb97a28554bc04a63b39569/hamilton/execution/executors.py#L80

**Describe alternatives you've considered**
...

**Additional context**

**Comment by 149189** [comment]
I Would Like To Work On this Bug
