### ISSUE TITLE
pandas stata

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#377]
Implement https://pandas.pydata.org/docs/reference/io.html#stata as a data loader & saver.

1. It should go into pandas_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [pandas pickle reader and writer](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) are structured.
2. There should be requisite tests to exercise the functionality. If it's simpler just write one function that saves and then reads in the stata file.
3. Assuming there is no weird dependency required to run it, place it in with the other materialization examples.
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by JoJo10Smith** [comment]
I will be working on this ticket.

Thanks
Jordan

**Comment by skrawcz** [comment]
implemented! Thanks!
