### ISSUE TITLE
pandas feather (need to expose all params)

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#384]
Adjust the existing feather implementation to match https://pandas.pydata.org/docs/reference/io.html#feather as a data loader & saver.

1. Modify the implementation in pandas_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [pandas pickle reader and writer](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) are structured.
2. There should be requisite tests to exercise the functionality. We should move to using a single test if possible -- one that writes and then reads.
3. Add to the pandas materializer example showing writing of a pandas dataframe.
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by JoJo10Smith** [comment]
Taking this ticket!

**Comment by skrawcz** [comment]
merged!
