### ISSUE TITLE
pandas table

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#407]
Implement https://pandas.pydata.org/docs/reference/io.html#flat-file (read_table) as a data loader

1. It should go into pandas_extensions.py, one class for the reader, e.g. much like how the [pandas pickle reader](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) is structured.
2. There should be requisite tests to exercise the functionality.
3. If there's an issue with type hints, let me know and we can chat through it.

Note: there is not pandas.to_table here, so only a "reader" is required.

**Comment by 149189** [comment]
Hey! I would Like to Work on this issue can you please assign me.

**Comment by skrawcz** [comment]
@149189 let me know if you need help/have questions.

**Comment by 149189** [comment]
@skrawcz Thanks! I will let you know.

**Comment by skrawcz** [comment]
@149189 you basically just need to emulate something similar in structure to https://github.com/DAGWorks-Inc/hamilton/pull/416/files#diff-006cf9e6605a81f7a82ff7cdfa962e64a7ee02b763b388c87bde4fa424bb4e34R86-R249.

**Comment by skrawcz** [comment]
@149189 let me know if you're still working on this, otherwise I'm allowing someone else to take it.

**Comment by bengineerdavis** [comment]
I'd like to take a shot at it!

**Comment by muhd360** [comment]
hi can this issue be assigned to me

**Comment by skrawcz** [comment]
> hi can this issue be assigned to me

@muhd360 not right now. I just assigned to @bengineerdavis. We have other issues that I could point you to instead?

**Comment by skrawcz** [comment]
@swapdewalkar if you comment I can assign this to you thanks
