### ISSUE TITLE
Want to update your readme.md 

### ISSUE THREAD

**Issue by sb-decoder** [DAGWorks-Inc/hamilton#408]
**Is your feature request related to a problem? Please describe.**
Currently, your repo has contributor names in the README.md , I want to add those names with their profile pics , which will be updated automatically

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skrawcz** [comment]
@sb-decoder sounds interesting. 
1. Can you point me to an example of what you want to do please?
2. Can you explain how it will auto-update? 

Thanks for the issue!

**Comment by skrawcz** [comment]
Closing due to no movement.
