### ISSUE TITLE
[good first issue - beginner] Polars Readers & Writers

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#410]
**Is your feature request related to a problem? Please describe.**
We need to add Polars Readers & Writers (Savers & Loaders in our internal parlance).

**Describe the solution you'd like**
We need to have readers & if appropriate, writers that cover I/O listed [here](https://pola-rs.github.io/polars/py-polars/html/reference/io.html):

- [x] #421
- [x] #417
- [x] #449
- [x] #418
- [x] #420
- [x] #450
- [ ] Delta lake

Example implementation to mirror can be [found here](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L57-L234).

**Additional context**
We need to start building wrappers around the common ways people will want to save/load data. That way they'll have off the shelf ways to get onto Hamilton easily.

# If you're interested in contributing

If you are interested in contributing, picking up one of the above should be straightforward.

1. Ask for one, and we'll assign it.
2. We'll create an issue for you.
3. We'll then work with you on that issue.

In terms of effort, for an example of a desired class, see [this code](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L57-L234). It basically involves:

1. Reading the subsequent documentation.
2. Creating the right class.
3. Creating some tests for it.
4. Creating an example to put into our examples repository.

**Comment by swapdewalkar** [comment]
@skrawcz I'll take this up!

**Comment by kokobhara** [comment]
Is this issue assigned as a whole or can we take up individual components from the list (Parquet, JSON, etc.) similar to #284 ?

**Comment by skrawcz** [comment]
> @skrawcz I'll take this up!

@swapdewalkar let me know which one you want to take.

> Is this issue assigned as a whole or can we take up individual components from the list (Parquet, JSON, etc.) similar to https://github.com/DAGWorks-Inc/hamilton/issues/284 ?

@kokobhara correct, like #284. I will break it up into components as people ask for bits.

**Comment by swapdewalkar** [comment]
@skrawcz I can start with json and parquet.

**Comment by skrawcz** [comment]
> @skrawcz I can start with json and parquet.

Sure! Please comment on #417 and #418 to have me assign it to you.

**Comment by kokobhara** [comment]
@skrawcz Can I take this up for Avro?

**Comment by skrawcz** [comment]
> @skrawcz Can I take this up for Avro?

Sure - please comment on https://github.com/DAGWorks-Inc/hamilton/issues/420 so I can assign it to you.

**Comment by somaiyamansi** [comment]
Hello, I'd like to work on Feather/IPC

**Comment by skrawcz** [comment]
> Hello, I'd like to work on Feather/IPC

@somaiyamansi please comment on https://github.com/DAGWorks-Inc/hamilton/issues/421

**Comment by swapdewalkar** [comment]
@skrawcz Assign Spreadsheet and Database to me, I have already started working on them.

**Comment by skrawcz** [comment]
> @skrawcz Assign Spreadsheet and Database to me, I have already started working on them.

@swapdewalkar  #449 and #450 are yours.
