### ISSUE TITLE
Polars AVRO reader/writer

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#420]
Implement https://pola-rs.github.io/polars/py-polars/html/reference/io.html#avro as a data saver/loader.

1. It should go into polars_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [polars csv reader and writer ](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L57-L234) are structured.
2. There should be requisite tests to exercise the functionality. We can do one test that writes & then reads it's own output.
3. Then an example should be added to a new directory called `materialization` under [example/polars](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/polars/). It should mirror the [pandas materialization example](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/pandas/materialization) in structure.
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by kokobhara** [comment]
Hi @skrawcz ,  I'll take this up.

**Comment by skrawcz** [comment]
merged. Thanks @kokobhara !

**Comment by skrawcz** [comment]
done in. (#447 )
