### ISSUE TITLE
Polars: Read & write to a database

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#449]
Implement https://pola-rs.github.io/polars/py-polars/html/reference/io.html#database as a data saver/loader. i.e. [Read](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_database.html) & [write](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_database.html) to a [database](https://pola-rs.github.io/polars/user-guide/io/database/).

1. It should go into polars_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [polars csv reader and writer ](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L57-L234) are structured.
2. There should be requisite tests to exercise the functionality. We can do one test that writes & then reads it's own output.
3. Then an example should be added to the existing materialization example under [example/polars](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/polars/materialization).
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by swapdewalkar** [comment]
@skrawcz Working on this.

**Comment by skrawcz** [comment]
@swapdewalkar any updates ? :)

**Comment by swapdewalkar** [comment]
@skrawcz I will try to finish this week?

**Comment by skrawcz** [comment]
Done. Thanks @swapdewalkar !
