### ISSUE TITLE
Polars: reada/write spreadsheet materializer

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#450]
Implement https://pola-rs.github.io/polars/py-polars/html/reference/io.html#spreadsheet as a data saver/loader. i.e. [Read](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html#polars.read_excel) & [write](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_excel.html#polars.DataFrame.write_excel) to a spreadsheet.

1. It should go into polars_extensions.py, one class for the writer, on class for the reader, e.g. much like how the [polars csv reader and writer ](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/polars_extensions.py#L57-L234) are structured.
2. There should be requisite tests to exercise the functionality. We can do one test that writes & then reads it's own output.
3. Then an example should be added to the existing materialization example under [example/polars](https://github.com/DAGWorks-Inc/hamilton/tree/main/examples/polars/materialization).
4. If there's an issue with type hints, let me know and we can chat through it.

**Comment by skrawcz** [comment]
Completed. Thanks @swapdewalkar  🚀 ! Let me know if you want to take something else on!

**Comment by swapdewalkar** [comment]
@skrawcz Yes, let me know where I can help!

**Comment by skrawcz** [comment]
> @skrawcz Yes, let me know where I can help!

Sure. Maybe something from https://github.com/DAGWorks-Inc/hamilton/issues/786? Or perhaps there's another issue you're interested in?
