### ISSUE TITLE
[good first issue - intermediate] Plot Materializer for Sklearn Plots

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#456]
**Is your feature request related to a problem? Please describe.**
It is common for debugging scenarios in machine learning to produce plots for debugging purposes as a pipeline runs. You can do this with Hamilton, but we believe the ergonomics could be improved with [materializers](https://hamilton.dagworks.io/en/latest/concepts/driver-capabilities/#materializing-dag-nodes).

**Describe the solution you'd like**
Given the following Hamilton functions:
```python
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

def y_pred(clf: Classifier, X_test: pd.Dataframe) -> pd.Series:
     return clf.predict(X_test)

def confusion_matrix(y_test: pd.Series,  y_pred: pd.Series) -> np.ndarray:
    return confusion_matrix(y_test, y_pred)

def cm_display(confusion_matrix: np.ndarray) -> ConfusionMatrixDisplay:
      return ConfusionMatrixDisplay(cm).plot()
```
We want to capture `cm_display` and save the produced plot somewhere.

One possible [materializer](https://hamilton.dagworks.io/en/latest/reference/drivers/Driver/#hamilton.driver.Driver.materialize) API:
```python
to.png(
   id="foo_bar_confusion_matrix",
   dependencies=["cm_display"]
   path="./foo_bar_confusion_matrix.png"
   height=12,
   withd=12, # some sort of kwargs...
)
```
That would handle taking the object and creating a PNG from it. 

We should try to handle a few of the common plot types in sklearn.

**Describe alternatives you've considered**
You do this in the function -- but I think the materializer pattern helps abstract this.

**Comment by luahan77m** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by skrawcz** [comment]
@luahan77m sorry this issue has actually been done. I forgot to close it. Apologies. 

If you want a simple task - https://github.com/DAGWorks-Inc/hamilton/issues/247 - is a good one to get started with. It will require you to become familiar with the process of contributing to open source and so I recommend that as a place to start.
