### ISSUE TITLE
Single node cache using DataSaver/DataLoader

### ISSUE THREAD

**Issue by zilto** [DAGWorks-Inc/hamilton#461]
**Is your feature request related to a problem? Please describe.**
When developing code interactively and running it to see if new functions work or not, I find myself commenting in/out sections of my code with materializers and inputs to test faster my new functions.

**Describe the solution you'd like**
Essentially, I would need a "run once" mechanism. If the artifact exist, load it; otherwise, run required upstream nodes. This is a simpler approach than a full caching solution which cares about DAG version, config, inputs, etc.

API idea:
Decorate functions to cache a node result using a pair of data loader and data saver. 

```python
def scaled_df(raw_data: pd.DataFrame) -> pd.DataFrame:
  return pd.DataFrame()

# cache.parquet implements functions from load_from.parquet, save_to.parquet
# need to figure out how to pass specific reader/writer kwargs
@cache.parquet(path=value("train.parquet"))
def training_set(scaled_df: pd.DataFrame) -> pd.DataFrame:
  return scaled_df.loc[:100].copy()
```

**Describe alternatives you've considered**

**Additional context**

**Comment by elijahbenizzy** [comment]
@zilto just checking -- have you seen the caching graph adapter? https://hamilton.dagworks.io/en/latest/reference/graph-adapters/CachingGraphAdapter/.

Has basically this same API :) We need to unify it with the loader framework, but that's coming soon.

**Comment by zilto** [comment]
That makes sense! Closing issue
