### ISSUE TITLE
Display defaults on DAG viz

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#495]
**Is your feature request related to a problem? Please describe.**
It would be nice to know what's required, and what's not

**Describe the solution you'd like**
A `=X` afterwards for `X` where `str(X)` is short, otherwise `=...`

**Describe alternatives you've considered**
Not doing this?

**Additional context**
Seeing contrib stuff, this could help.

**Comment by zilto** [comment]
Adding a few notes for viz upgrade:
- All config node have type `Any`. We could display the value of the config node instead. For example `@config.when(task="classification")` generates node `Task \n classification" instead of `Task \n Any`

**Comment by zilto** [comment]
- configs are now displayed #833
- adding default values is tracked in #710
