### ISSUE TITLE
create_temporary_modules should error out with helper (`_`) functions

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#510]
If we create_temporary_modules with an underscore function it should not work. It will not get turned into a function, and the function can refer to a helper function regardless.

This can help the ad-hoc case.

**Comment by skrawcz** [comment]
I don't understand? You pass in the functions with create_temporary_modules? Why not just prevent people passing in `_` ones?

**Comment by elijahbenizzy** [comment]
> I don't understand? You pass in the functions with create_temporary_modules? Why not just prevent people passing in `_` ones?

Yep, that's what this issue suggests. It curerntly does work, and gets weird results, but it shouldn't.

**Comment by elijahbenizzy** [comment]
This is complete! https://github.com/DAGWorks-Inc/hamilton/pull/558
