### ISSUE TITLE
Feast integration example type error

### ISSUE THREAD

**Issue by neverfox** [DAGWorks-Inc/hamilton#575]
The "Hamilton pattern" cell of [`retrieval.ipynb`](https://github.com/DAGWorks-Inc/hamilton/blob/main/examples/feast/integration_feature_store/feature_repo/retrieval.ipynb) for the Feast integration example fails with a ValueError related to the type of `trips_stats_3h_path`.

# Current behavior

```
ValueError: Error: trips_stats_3h_source is expecting trips_stats_3h_path:<class 'str'>, but found trips_stats_3h_path:typing.Union[str, pathlib.Path, _io.BytesIO, _io.BufferedReader]. 
Hamilton does not consider these types to be equivalent. If you believe they are equivalent, please reach out to the developers.Note that, if you have types that are equivalent for your purposes, you can create a graph adapter that checks the types against each other in a more lenient manner.
```

## Steps to replicate behavior
1. Run all cells of [`examples/feast/integration_feature_store/feature_repo/retrieval.ipynb`](https://github.com/DAGWorks-Inc/hamilton/blob/main/examples/feast/integration_feature_store/feature_repo/retrieval.ipynb)

## Library & System Information
Python 3.11.6
Feast 0.34.1
Hamilton 1.39.0
MacOS 13.5

# Expected behavior
The notebook should run without errors and the final cell should show the `historical_features` output.

# Additional context
The example was run as is on the

**Comment by skrawcz** [comment]
Thanks @neverfox I have replicated the issue. Will hopefully have a triage for it later today. Thanks for filing!

**Comment by skrawcz** [comment]
@neverfox I have a fix. Just need to clean it up. ETA Monday.

**Comment by skrawcz** [comment]
@neverfox the latest Hamilton 1.39.1 should fix this -- please reopen if that's not the case :)
