### ISSUE TITLE
Displaying source code of Node on Graphviz node

### ISSUE THREAD

**Issue by alechewitt** [DAGWorks-Inc/hamilton#582]
**Is your feature request related to a problem? Please describe.**
I have a use case where I want to display the python code of the Hamilton Node in the graph image when calling `visualize_execution`. This is specifically for nodes with the same name, but different implementation. See this contrived example:
```python
@config.when(location='USA')
def display_price__USA(raw_cost:pd.Series, profit_margin: pd.Series) -> pd.Series:
    """Prices are display without taxes"""
    return raw_cost + profit_margin

@config.when(location='UK')
def display_price__UK(raw_cost: pd.Series, profit_margin: pd.Series) -> pd.Series:
    """Prices in the UK are displayed with the 20% VAT tax"""
    return (raw_cost + profit_margin) * 1.2
```

In the visualized Graph, there is no way to see the different calculation being used for the UK `display_price` vs the US `display_price`. I would like the graphviz node to display `raw_cost + profit_margin` or `(raw_cost + profit_margin) * 1.2` on it. 

**Describe the solution you'd like**
This could be implemented with a new decorator called something like `display_options`. eg:
```python
@config.when(location='UK')
@display_options(show_code=True)
def display_price__UK(raw_cost: pd.Series, profit_margin: pd.Series) -> pd.Series:
    """Prices in the UK are displayed with the 20% VAT tax"""
    return (raw_cost + profit_margin) * 1.2
```
Under the hood this could be implemented with a [tag](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/node.py#L55) on the Node. It would work very similar to the [tag decorator](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/function_modifiers/metadata.py#L9), however instead of allowing any arbitrary tags, it only allowed predefined tags. Then when the [label is being created for the graphviz node](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/graph.py#L199-L214) we could check if the predefined tags existed and modify the label accordingly. The actual code would be retrieved with the Python [inspect module](https://docs.python.org/3/library/inspect.html#inspect.getsource).

In the future, the `display_options` decorator could be extended with other options for the graph visualization. 

If more flexibility is required, `show_code` doesn't have to be a boolean. Instead it could be a list of integers, where each integer indicates which line of code to display.

**Describe alternatives you've considered**
None

**Additional context**
If this is a feature that you think you might want, I am happy to have a go at implementing it and creating a PR.

**Comment by skrawcz** [comment]
@alechewitt thanks -- just to understand the root motivation. Is it because given a DAG instantiation, you don't know which implementation is being used?  

If so, would it suffice to (a) mark the node as configuration driven, and (b) show the function name it actually maps to instead? I'm just thinking about graph readability versus showing source code that could make it harder to read.

**Comment by skrawcz** [comment]
Okay thanks for the offline context @alechewitt .

So yeah then the question really is:

1. what are the predefined tags? It's easier to add than remove, so we could start small.
2. I think extending the tag decorator is the way to go -- likely adding a namespace or something for these tags to not collide with any user ones.

**Comment by skrawcz** [comment]
Right now -- with the JSON export feature, one can adjust the graphviz visualization object returned with whatever information one wants. Will close this for now, unless there's more movement to bring something like this into the library natively.
