### ISSUE TITLE
Allow non-strings in @tag(...)

### ISSUE THREAD

**Issue by kzk2000** [DAGWorks-Inc/hamilton#620]
```@tag(business_line=<must be a string here>)``` doesn't currently allow for non-strings.
I'd would be great if, say, a list of strings would also work, so I could do something this ```@tag(business_line=["US", "CA"])``` 

and then leverage that later with a wrapper like this ```dr.list_available_variables(tag_filter={"business_line" : "US"})``` or similar

**Describe alternatives you've considered**
Write my own ```@custom_tag()``` derived from ```@tag``` class that disables the "str" type check. Doable but preferably I don't go off tangent with custom code and Hamilton just supports this out of the box.

**Comment by elijahbenizzy** [comment]
Agreed that we should allow for some structure here. I think we have two choices:
1. Allow any arbitrary json here
2. Allow some specific structure that has semantic meaning.

I'm going to recommend (2). In this case:
- strings assign a value to the tag
- lists assign multiple values to the tag

Then we have a query system (suggested in [here](https://github.com/DAGWorks-Inc/hamilton/issues/37)) that allows you to query for nodes that match tags. With simple `=`, `in`, `not =`, `not in` type operations. The driver maintains a list and can do the queries for you. I don't really foresee the need for anything more complex, and this matches the common configuration patterns...

**Comment by kzk2000** [comment]
> [...] that match tags with simple =, in, not =, not in type operations.

this was exactly where I was going with this, works for me!

**Comment by skrawcz** [comment]
also - https://github.com/DAGWorks-Inc/hamilton/issues/293.

**Comment by skrawcz** [comment]
Otherwise I think lists of strings seem to be fine. Can't seem to recall why we didn't do this in the first place.

The other -- nested dicts can already be done with the namespacing/dot stuff.

```
@tag(**{'my.tag': 'tag_value'})
       def my_function(...) -> ...:
```

**Comment by skrawcz** [comment]
@kzk2000 want to take https://github.com/DAGWorks-Inc/hamilton/pull/622 for a spin?
