### ISSUE TITLE
Lifecycle Validators

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#631]
**Is your feature request related to a problem? Please describe.**
We want to be able to add custom validation for nodes/DAGs

**Describe the solution you'd like**
Two hooks:
- `validate_node`
- `validate_graph`
 
That can raise an exception.

**Describe alternatives you've considered**
Sticking it in a method/hook.

**Additional context**
Thinking about more enterprise-level concerns.

**Comment by skrawcz** [comment]
@elijahbenizzy this is done, right?
