### ISSUE TITLE
Change node hooks to take in HamiltonNode

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#661]
**Is your feature request related to a problem? Please describe.**
[StaticValidator](https://github.com/DAGWorks-Inc/hamilton/blob/788040a6217165f36c3bd3e3316f6884f924a4ad/hamilton/lifecycle/api.py#L545) does, but the rest don't. We should fix this. We just need to keep it backwards compatible, and we can do this with `**future_kwargs`. Possibly log a warning as well.

**Describe alternatives you've considered**
Keeping it the way it is

**Additional context**
API consistency

**Comment by zilto** [comment]
I believe this can be closed?
