### ISSUE TITLE
Can't save DAG file in subdirectories

### ISSUE THREAD

**Issue by abajorat** [DAGWorks-Inc/hamilton#687]
https://github.com/DAGWorks-Inc/hamilton/blob/e5f4f32b6f1f7d1fc61d841818ba9f680cbfd8de/hamilton/graph.py#L859

This line of code, where the output_file_path is split and then assigned to itself, does not allow storing the DAG file in subdirectories to keep the project clean.
I think I can find a workaround by assigning arguments to kwender_args, but it would be great if you could fix this :)

**Comment by skrawcz** [comment]
Are you providing a relative path? or? This should only strip the extension and leave the path intact -- I will verify that though.

**Comment by skrawcz** [comment]
@abajorat can you provide an example of the function call you're providing? 

Do you mean you were keeping the "dot" files separate from the image? or?

**Comment by skrawcz** [comment]
@abajorat there was also a regression in the `1.46.0` & `1.47.0` releases where paths were being stripped. What version of Hamilton are you on?

**Comment by abajorat** [comment]
you're right, I'm on the wrong version then, sorry
Thanks for the clarification!

**Comment by skrawcz** [comment]
@abajorat no worries -- thanks for raising and sorry for allowing the regression!
