### ISSUE TITLE
VSCode Extension can't register modules

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#718]
It seems the current VSCode extension is busted.

# Current behavior
Can't seem to register modules and thus use the extension.

## Stack Traces
(If applicable)

## Screenshots
(If applicable)

## Steps to replicate behavior
1. Install extension
2. Can't select modules for use with the extension.

## Library & System Information
Windows, Mac both recreated this issue.

# Expected behavior
We can click and add modules.

# Additional context

**Comment by zilto** [comment]
let's manage these under the vscode [extension repo](https://github.com/zilto/vscode-hamilton)? I discourage sharing / showcasing the extension until we allocate some time to scope features, do some bug fix, and add some basic tests
