### ISSUE TITLE
Standardize API for dataflow and node versioning

### ISSUE THREAD

**Issue by zilto** [DAGWorks-Inc/hamilton#728]
Currently, there are at least 3 sets of features that rely on dataflow and node versioning:
- the CLI `version` command and its underlying logic ([see here](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/cli/logic.py#L62)) which outputs a dictionary / JSON of nodes and dataflow versions. Node versioning is based on the hash of the originating function using `graph_utils.hash_source_code()`. The dataflow version is derived from the dictionary of `{node_name: node_version}`.
- the `h_diskcache.DiskCacheAdapter` also uses `graph_utils.hash_source_code()` to version the node's originating function. The cache key is derived from `(node_hash, input_1, input_2, ..., input_n)`
- the `h_experiments.hook.ExperimentTracker` preceeded the two other features. Therefore, it has its own `h_experiments.hook.graph_hash()` function. It creates a hash from the dictionary of node originating functions. It should leverage the same logic as the CLI.

# Solution design
- does it make sense to have `hash_source_code()` under `graph_utils`? If yes, we could add `hash_node()` and `hash_dataflow()`
- it could make sense as properties for `graph_types.HamiltonNode` and `graph_types.HamiltonGraph`
- disambigue terms around "hash", "version", "node", "function", "originating_function"

**Comment by elijahbenizzy** [comment]
I don't think people should be using `graph_utils` as part of the API -- I like having properties on the `graph_types` to compute these in a "blessed" way.
