### ISSUE TITLE
Add @post_pipe

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#749]
**Is your feature request related to a problem? Please describe.**
`@pipe` is nice, but can be a little counter-intuitive to read. i.e. the function parameter declares the dependency, is then modified by `@pipe` and then passed into the function.

**Describe the solution you'd like**
`@post_pipe` would be the opposite of `@pipe`. The function would declare the dependency, the body of the function would run, and then the `@post_pipe` steps would run after the function.

```python
@post_pipe(# these run after the function is run.
    step(_transform_1, v=1),
    step(_transform_2, v=2),
)
def A_processed(A: pd.DataFrame) -> pd.DataFrame:
    return A # original A -- could do modifications here.
```

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by elijahbenizzy** [comment]
@skrawcz this is a duplicate https://github.com/DAGWorks-Inc/hamilton/issues/701
