### ISSUE TITLE
Pandas spss

### ISSUE THREAD

**Issue by swapdewalkar** [DAGWorks-Inc/hamilton#813]
Check Parent [#284](https://github.com/DAGWorks-Inc/hamilton/issues/284)
Implement https://pandas.pydata.org/docs/reference/io.html#read_spss as a data loader

 1.   It should go into pandas_extensions.py, one class for the reader, e.g. much like how the [pandas pickle reader](https://github.com/DAGWorks-Inc/hamilton/blob/main/hamilton/plugins/pandas_extensions.py) is structured.
 2.  There should be requisite tests to exercise the functionality.
 3.  If there's an issue with type hints, let me know and we can chat through it.

Note: there is not pandas.to_spss , so only a "reader" is required.

**Comment by skrawcz** [comment]
done. thanks!
