### ISSUE TITLE
save_to.parquet strips URI prefix when decorated from a resolve_from_config wrapper

### ISSUE THREAD

**Issue by janhurst** [DAGWorks-Inc/hamilton#923]
I am using a @resolve_from_config wrapper to decorate a function when config is available with a parquet data saver.

I am attempting to pass in some config to build the path to save to. However when decorating this way the URI like path that I am building is stripped... ie my `gs://bucket/dir/file` turns into `bucket/dir/file` which fails

My decorator looks something like:

```
@resolve_from_config(
    decorate_with=lambda experiment_id: save_to.parquet(
        path=f"gs://{BUCKET}/{experiment_id}/curated.parquet"
    )
)
```
A plain decorator like such works just fine:

```
@save_to.parquet(path=f"gs://{BUCKET}/my-experiment/curated.parquet")
```

## Library & System Information
python 3.11
hamilton 1.61

# Expected behavior
The `gs://` uri prefix should not be stripped when called via the resolve_from_config approach

**Comment by elijahbenizzy** [comment]
@janhurst interesting. This is weird as the resolve shouldn't care about the parameter contents at all.

Happy to take a look -- it would help speed up debugging if you have a full script that runs a minimal example (ideally a single file, with an assert that fails). 

You can use `ad_hoc_utils.create_temporary_module` to create a module from the fn + run it in one file, or do `import __main__` and create the driver from that.

**Comment by janhurst** [comment]
Hi, I've tried to reproduce this even locally after being prompted by Stefan. And I can't :~(

I don' t know if I had something odd going on in my code that I hadn't picked up on, but putting in a @resolve_from_config decorator is now working here and the `gs://` protocol is not being stripped

i'm really sorry for the noise :~(
