### ISSUE TITLE
Add google collab links for all notebooks

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/hamilton#934]
We should add google collab links for all notebook examples that we have.

Task:

1. Add the google collab badge and link to the notebook & README to all notebooks.
See https://openincolab.com/ for link & badge generation.

**Comment by zilto** [comment]
Colab links can be generated by replacing `github.com` with `githubtocolab.com`. To run on Google Colab, notebooks will need a statement to `pip install -r requirements.txt`

**Comment by skrawcz** [comment]
yep - I did it last night. Not everything is amenable to it.
