### ISSUE TITLE
`PandasExcelWriter` overwrites file 

### ISSUE THREAD

**Issue by zilto** [DAGWorks-Inc/hamilton#946]
A user would like to create multiple `to.excel()` materializers and have each write to a separate Excel sheet. Currently, each materializer overwrite the previous file.

# Expected behavior
The `save_data()` should use pandas's `ExcelWriter` instead of `.to_excel()` because it allows `if_sheet_exists={‘error’, ‘new’, ‘replace’, ‘overlay’}`.

Will have to make sure all kwargs are backwards compatible given `ExcelWriter` takes less arguments.

ref: https://pandas.pydata.org/docs/reference/api/pandas.ExcelWriter.html

# Additional context

**Comment by lohithasiripurapu** [comment]
Hi, is anyone working on this issue? can you assign it to me?

**Comment by skrawcz** [comment]
@lohithasiripurapu sorry, but it seems like @noahridge has a start here. I just can't assign it to them until the comment on this issue.

**Comment by noahridge** [comment]
@skrawcz Yep, I will finish up the pull request for this issue shortly.

**Comment by skrawcz** [comment]
this will be pushed next release
