### ISSUE TITLE
display `DataLoader` as materializer in viz

### ISSUE THREAD

**Issue by zilto** [DAGWorks-Inc/hamilton#988]
The `DataLoader` doesn't match the `DataSaver` display

![image](https://github.com/DAGWorks-Inc/hamilton/assets/68975210/d1f6883a-69a0-43a8-bb71-3556522c555f)

**Comment by elijahbenizzy** [comment]
How hard would it be to add a `raw` mode? E.G> one that just displays the graph in a plain way?

**Comment by zilto** [comment]
By "raw", you mean "no formatting"? It think this should already be feasible through the exposed `graphviz_kwargs` and `render_kwargs`, but would have to double check

The PR for this change was merged though.

**Comment by skrawcz** [comment]
> How hard would it be to add a `raw` mode? E.G> one that just displays the graph in a plain way?

that's a different issue than this one. So closing this as completed.
